script:
  - 'bundle exec rspec'
env:
  - 'SENDGRID_PASSWORD=123 SENDGRID_USERNAME=123 DEVISE_SECRET_KEY=123 SECRET_TOKEN=123 MONGO_URI=localhost:27017'
branches:
  only:
    - master
rvm:
  - 2.5.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
services:
  - mongodb
before_install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.3'
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
