script:
  - 'bundle exec rspec'
env:
  - 'SENDGRID_PASSWORD=123 SENDGRID_USERNAME=123 DEVISE_SECRET_KEY=123 SECRET_TOKEN=123'
branches:
  only:
    - master
rvm:
  - 2.4.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
services:
  - mongodb
before_install:
 - gem update bundler
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
